@startuml
left to right direction
:User: as user
:New User: as new   
:Returning User: as ret
:E-Scooter: as scooter
new --|> user
ret --|> user
rectangle E-Scooter_App {
  (login) as li
  (sign up) as su
  (verify age) as va
  (verify\npassword) as vp
  (login error) as le
  (remove scooter from\ncharging station) as rsfcs
  (scooter powers on) as spo
  (scooter charges in\ncharging station) as scics
  (scooter returned to\ncharging station) as srtcs
  (payment taken) as pt
  (mark scooter\nas broker) as msab
  su .> va : includes
  li .> vp : includes
  le .> li : extends
  rsfcs .> spo : includes
  srtcs .> scics : includes
  srtcs .> pt : includes
}
ret --- li
new --- su
user -- rsfcs
spo --- scooter
user --- srtcs
scics --- scooter
user --- msab
@enduml
